sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: test_root

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: sky-take-out